### ISSUE TITLE
DSL Link Status Dashboard

### ISSUE THREAD

**Issue by mrcsdl** [sberk42/fritzbox_exporter#12]
Hey, i set up your exporter but in the Grafana Dashboard the DSL Link Status looks kinda bugged.

![image](https://user-images.githubusercontent.com/24762590/154925361-274d3c13-16d9-49d4-841f-38b133649e24.png)
Can you help me with that?

Greeting

**Comment by olmo1501** [comment]
Looks like you did some changes to the Prometheus Job. Shorten your time range and see if that kind of fixes it. If yes you just need to wait.

**Comment by mrcsdl** [comment]
> Looks like you did some changes to the Prometheus Job. Shorten your time range and see if that kind of fixes it. If yes you just need to wait.

you mean in the prometheus.yml?

**Comment by mrcsdl** [comment]
`global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # Example job for node_exporter
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
 
  # Example job for fritzbox-prometheus-exporter
  - job_name: 'fritzbox-prometheus-exporter'
    static_configs:
      - targets: ['192.168.178.52:9042']
  # Example job for cadvisor
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
`

This is my prometheus.yml

**Comment by mrcsdl** [comment]
scrape_interval: 15s # By default, scrape targets every 15 seconds.

Attach these labels to any time series or alerts when communicating with
external systems (federation, remote storage, Alertmanager).
external_labels:
monitor: 'codelab-monitor'
A scrape configuration containing exactly one endpoint to scrape:
Here it's Prometheus itself.
scrape_configs:

The job name is added as a label job=<job_name> to any timeseries scraped from this config.
job_name: 'prometheus'
Override the global default and scrape targets from this job every 5 seconds.
scrape_interval: 5s
static_configs:
targets: ['localhost:9090']
Example job for node_exporter
job_name: 'node_exporter'
static_configs:
targets: ['node_exporter:9100']
Example job for fritzbox-prometheus-exporter
job_name: 'fritzbox-prometheus-exporter'
static_configs:
targets: ['192.168.178.52:9042']
Example job for cadvisor
- job_name: 'cadvisor'
static_configs:
- targets: ['cadvisor:8080']

This is my prometheus.yml

**Comment by olmo1501** [comment]
Did you do changes to it after you first set up the job?

What does Grafana display if you set the time range to 5 minutes?

**Comment by mrcsdl** [comment]
it shows this i delete the job and add it again maybe this helps
![image](https://user-images.githubusercontent.com/24762590/154936868-ea8cfa7c-010a-450c-bd27-bb1a211550ae.png)

**Comment by olmo1501** [comment]
In Grafana expand the query. Change:

`gateway_connection_status{connection="Physical Link"}`

to

`gateway_connection_status{connection="Physical Link",interface="DSL"}`

**Comment by mrcsdl** [comment]
this worked. Thanks

btw is it normal if i hover with my mouse over one graph it selects in every graph?

![image](https://user-images.githubusercontent.com/24762590/154939040-68ba9bac-7984-44e7-ba44-2dad47734953.png)

**Comment by mrcsdl** [comment]
That worked thanks.

Btw is it normal that it normal when i hover over one graph that it shows the stats on every graph.

![Unbenannt](https://user-images.githubusercontent.com/24762590/154939174-0160c674-2e5c-4e99-b831-ff2cc6caa3f3.png)

**Comment by olmo1501** [comment]
This is way out of scope for a Github issue, this is not a communications platform.

To answer your question: in the dashboard settings change "Graph Tooltip" to something other than "Shared Tooltip"

**Comment by mrcsdl** [comment]
Okay, sorry. I will close this issue. Thanks for your help!
