### ISSUE TITLE
Error during start

### ISSUE THREAD

**Issue by mentex23** [sberk42/fritzbox_exporter#15]
Hey,

I receive the following when I try the docker

i ran it with:

docker run -e 'USERNAME=myUsername' \
    -e 'PASSWORD=myPassword' \
    -e 'GATEWAY_URL="http://192.168.178.1:49000"' \
    -e 'LISTEN_ADDRESS="0.0.0.0:9042"' \
    fritzbox-prometheus-exporter:latest

an get:

time="2022-03-05T16:25:05Z" level=error msg="invalid URL:%!(EXTRA *url.Error=parse \"\\\"http://192.168.178.1:49000\\\"\": first path segment in URL cannot contain colon)"

**Comment by olmo1501** [comment]
Please see Issue #13

**Comment by mentex23** [comment]
look good now.. thanks.. Am I right that i need to install prometheus separately?

**Comment by mentex23** [comment]
I do not get any data with:

**Comment by jobenvil** [comment]
It works. Having same Fritzbox.

**Comment by mentex23** [comment]
good to know.. Thanks for the "help":)

**Comment by olmo1501** [comment]
Try to connect to the container‘s IP not localhost if you are running the curl-command outside of the container.

**Comment by mentex23** [comment]
Thanks! That worked..

**Comment by DaZzLa09** [comment]
hey, i also struggled with this and thanks to your issue i got it running.
But how can i access this data with grafana?

**Comment by mentex23** [comment]
My Datasource looks like this.. The IP is the IP of my rPi

<img width="752" alt="Bildschirmfoto 2022-04-22 um 19 26 18" src="https://user-images.githubusercontent.com/38594479/164764500-f79c1db6-5527-4b19-9888-9fdd7058b474.png">
