### ISSUE TITLE
Add gateway-luaurl to the Using docker info

### ISSUE THREAD

**Issue by SirFlour** [sberk42/fritzbox_exporter#27]
hello sberk42, many thanks for the great work and sharing your project. i just wanted to add some info, which might help also others.

i have 2 fritzboxes and i was able to connect to both (2 docker container running). however, the lua info (cpu, temp etc) were always the same.

I found out, that the default lua was taken and so i needed to add gateway-luaurl. Maybe you can add that, so that others can easily find it. Many thanks and have nice day!

**Comment by sberk42** [comment]
just add it

**Comment by SirFlour** [comment]
Cool thanks a lot. i can confirm, it is now in the docker and working very well :) many thanks for your great support!
