### ISSUE TITLE
Prometheus exceeded maximum resolution of 11,000 points or empty result

### ISSUE THREAD

**Issue by iamatulsingh** [sberk42/fritzbox_exporter#28]
It's an awesome work I would say. I tried this and everything working but if you try to get the metrics of past 2 days or later, it will eventually fail with the error *"Prometheus exceeded maximum resolution of 11,000 points or empty result"* for some metrics such as *"Total Download"* or *"Total Upload"*.

**Comment by olmo1501** [comment]
What is failing? Grafana? If so: what is the selected timeframe?

**Comment by iamatulsingh** [comment]
I think it's Prometheus and hence Grafana. Timeframe is 2 days.

**Comment by olmo1501** [comment]
How often do you poll?

But after all you seem to be running an old Prpmetheus version. See https://github.com/prometheus/prometheus/issues/2253

**Comment by iamatulsingh** [comment]
<img width="1509" alt="Screenshot 2023-06-05 at 17 40 57" src="https://github.com/sberk42/fritzbox_exporter/assets/20820833/0adec596-59b9-4ded-abbe-c9c50ae1d4b4">

Here you can check the actual detail.

**Comment by sberk42** [comment]
the dashboard normally has a hard coded limit of max datapoints 10000 to avoid this issue

check the panels query options - probably it is messed up

**Comment by olmo1501** [comment]
I think the main "problem" is within Prometheus scrape interval. More than 11000 points in a 2 day timeframe would mean scraping about every 10 - 15 seconds which is way too much. My observation is that there are values a Fritzbox is updating every 3 minutes so tht would be a good starting point.

Also remember Pormetheus' hardcoded limit of 11000 datapoints per query as mentioned earlier on.

**Comment by iamatulsingh** [comment]
hardcoded limit is a problem but may be some other way to fix this. I tried rate but that's not good.
