### ISSUE TITLE
No Data on gateway_data_ecostat Panels (FB7490, 7.56OS)

### ISSUE THREAD

**Issue by F3LIX95** [sberk42/fritzbox_exporter#30]
Panels for CPU Temp, Utilization and Energy Consumption showing "No Data". all other Panels are Working.
Found out all are Querying **"gateway_data_ecostat"**

My Setup:
- Fritzbox 7490 on FritzOS 7.56
- Prometheus: 2.45.0
- Grafana v9.5.1
- fritzbox_exporter image from May 17 

all of the Pods are Running on k3s in the same Namespace.

BR,
Felix

**Comment by olmo1501** [comment]
As you have rebooted after installing firmware 7.56 this could be the root cause: #20 Restart your exporter.

**Comment by F3LIX95** [comment]
Thanks. Tried that today. without success...

**Comment by F3LIX95** [comment]
Got it working by deleting my deployment on k3s and redeployed the fritz-exporter completely.
